DEBUG = True

DATABASE_NAME = 'mms_database'
DATABASE_TABLE_NAME = 'mms_table'
DATABASE_HOST = 'localhost'
DATABASE_USER = 'root'
DATABASE_PASSWORD = ''

FROM_DEFAULT_TIMESTAMP = 1609459200
TO_DEFAULT_TIMESTAMP = 1640908800

DEFAULT_COIN = 'ETH'
DEFAULT_RANGE = 20
